services:
  - type: web
    name: finance-dashboard
    env: docker
    region: frankfurt
    plan: free
    branch: backend
    healthCheckPath: /actuator/health
    dockerfilePath: finance-dashboard/Dockerfile
    rootDirectory: finance-dashboard
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: finance-dashboard-db
    databaseName: finance_pfi0
    plan: free
    region: frankfurt
