server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:${DB_URL}}
    username: ${JDBC_DATABASE_USERNAME:${DB_USERNAME}}
    password: ${JDBC_DATABASE_PASSWORD:${DB_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        generate_statistics: false
        order_updates: true
        jdbc:
          batch_size: 25
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1
    open-in-view: false
  messages:
    basename: messages
    encoding: UTF-8
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://finance-169399.netlify.app}

logging:
  level:
    org:
      springframework:
        security: INFO
        orm.jpa: INFO
        transaction: INFO
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
        engine: INFO
    graduate:
      finance_dashboard: INFO