server:
  port: ${PORT}
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        generate_statistics: true
        order_updates: true
        jdbc:
          batch_size: 25
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1
    open-in-view: false
  messages:
    basename: messages
    encoding: UTF-8
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

logging:
  level:
    org:
      springframework:
        security: INFO
        orm.jpa: DEBUG
        transaction: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        engine: DEBUG
    graduate:
      finance_dashboard: DEBUG